# Generated by Django 2.2.16 on 2020-09-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="publish_date",
            new_name="published_date",
        ),
    ]
